aropixel_blog_post_category:
  resource: "@AropixelBlogBundle/Controller/PostCategoryController.php"
  type:     annotation

aropixel_blog_post_index:
  path: /blog/post/
  controller: Aropixel\BlogBundle\Http\Action\Post\IndexPostAction

aropixel_blog_post_new:
  path: /blog/post/new
  controller: Aropixel\BlogBundle\Http\Action\Post\CreatePostAction

aropixel_blog_post_edit:
  path: /blog/post/{id}/edit
  controller: Aropixel\BlogBundle\Http\Action\Post\EditPostAction

aropixel_blog_post_delete:
  path: /blog/post/{id}
  controller: Aropixel\BlogBundle\Http\Action\Post\EditPostAction

aropixel_blog_post_status:
  path: /blog/post/{id}/status
  controller: Aropixel\BlogBundle\Http\Action\Post\StatusPageAction
