aropixel_blog_post:
  resource: "@AropixelBlogBundle/Controller/PostController.php"
  type:     annotation

aropixel_blog_post_category:
  resource: "@AropixelBlogBundle/Controller/PostCategoryController.php"
  type:     annotation

aropixel_blog_post_index:
  path: /blog/post/
  controller: Aropixel\BlogBundle\Http\Action\Post\IndexPostAction

aropixel_blog_post_new:
  path: /blog/post/new
  controller: Aropixel\BlogBundle\Http\Action\Post\CreatePostAction
